# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-QWos-bqSCXwnOkdiGVlXGhPGm5DgXbV
"""
#
# Install streamlit library

# Then import the library as usual in the script.
import streamlit as st
from Bio import Entrez, SeqIO


# Configurar el correo electrónico para el uso de Entrez
Entrez.email = "a223201128@unison.mx"


# Título de la aplicación
st.title("Obtener Secuencia de Aminoácidos de una Proteína")

# Entrada para el ID de la proteína
id_proteina = st.text_input("Ingresa el ID de la proteína (por ejemplo, NP_001278826.1):")

# Botón para ejecutar la búsqueda
if st.button("Obtener Secuencia"):
    if id_proteina:
        try:
            # Obtener los datos de la proteína en formato FASTA desde NCBI
            with Entrez.efetch(db="protein", id=id_proteina, rettype="fasta", retmode="text") as handle:
                record = SeqIO.read(handle, "fasta")
                secuencia_aminoacidos = record.seq

                # Mostrar los resultados
                st.subheader("Secuencia de Aminoácidos:")
                st.text(secuencia_aminoacidos)

                # Mostrar la longitud de la secuencia
                st.subheader("Longitud de la Secuencia:")
                st.write(f"{len(secuencia_aminoacidos)} aminoácidos")
        except Exception as e:
            st.error(f"Error al obtener la secuencia: {e}")
    else:
        st.warning("Por favor, ingresa un ID de proteína válido.")
        
#PROPORCION DE  ATOMOS

import matplotlib.pyplot as plt

# Datos de la proporción de átomos de las proteínas
proteins = {
    "Insulina": {"C": 258, "H": 384, "O": 114, "N": 64, "S": 6},
    "Glucagón": {"C": 153, "H": 225, "O": 49, "N": 40, "S": 2},
    "Hemoglobina": {"C": 2954, "H": 4664, "O": 832, "N": 780, "S": 8},
    "Colágeno": {"C": 1590, "H": 2515, "O": 435, "N": 380, "S": 6},
}

# Función para graficar
def plot_atom_proportion(protein_name, atom_counts):
    atoms = list(atom_counts.keys())
    counts = list(atom_counts.values())
    
    fig, ax = plt.subplots()
    ax.pie(counts, labels=atoms, autopct='%1.1f%%', startangle=90, colors=plt.cm.tab20.colors)
    ax.set_title(f"Proporción de átomos en {protein_name}")
    return fig

# Título
st.title("Proporción de átomos en proteínas")

# Descripción
st.write("Este programa muestra la proporción de átomos en diferentes proteínas. Selecciona una proteína para ver su gráfica.")

# Selección de proteína
selected_protein = st.selectbox("Selecciona una proteína:", list(proteins.keys()))

# Obtener datos de la proteína seleccionada
atom_data = proteins[selected_protein]

# Mostrar los datos en una tabla
st.subheader(f"Datos de {selected_protein}")
st.write(atom_data)

# Generar la gráfica
fig = plot_atom_proportion(selected_protein, atom_data)

# Mostrar la gráfica
st.pyplot(fig)

