# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-QWos-bqSCXwnOkdiGVlXGhPGm5DgXbV
"""

import streamlit as st
from Bio import SeqIO
from Bio.PDB import PDBList
from biopandas.pdb import PandasPdb
import plotly.express as px
import matplotlib.pyplot as plt

st.title("Visualización de Proteínas")
st.write("Esta es una aplicación de Streamlit para analizar datos de proteínas.")

# Código adaptado para Streamlit
pdb = PDBList()
pdb.retrieve_pdb_file('1ZEI', pdir='.', file_format='pdb')

ppdb = PandasPdb().read_pdb("1zei.pdb")
df_atomos = ppdb.df['ATOM']

st.write("Datos de átomos:")
st.dataframe(df_atomos.head())

st.write("Gráfico de factor B:")
fig, ax = plt.subplots()
ppdb.df["ATOM"]["b_factor"].plot(kind="line", ax=ax, color="pink", figsize=(10, 5))
st.pyplot(fig)